addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"              % "3.0.2")
addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"                % "1.5.12")
addSbtPlugin("com.typesafe"                      % "sbt-mima-plugin"               % "1.1.3")
addSbtPlugin("org.scala-js"                      % "sbt-scalajs"                   % "1.14.0")
addSbtPlugin("org.portable-scala"                % "sbt-scalajs-crossproject"      % "1.3.2")
addSbtPlugin("org.scala-native"                  % "sbt-scala-native"              % "0.4.16")
addSbtPlugin("org.portable-scala"                % "sbt-scala-native-crossproject" % "1.3.2")
